services:
  backend:
    build: ./backend
    env_file:
      - ./backend/.env
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
      - /var/run/docker.sock:/var/run/docker.sock
    depends_on:
      - db

  frontend:
    build: ./frontend
    ports:
      - "5173:5173"
    environment:
      - HOST=0.0.0.0
    depends_on:
      - backend

  db:
    image: postgres:15
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: calls
      POSTGRES_PASSWORD: callsdbpass
      POSTGRES_DB: callsdb
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
